"""Reproducible evaluation for the final PCB-defect detector.

Run only after placing the prepared YOLO dataset at ``dataset_final/``:

    python scripts/evaluate_model.py --data dataset_final/data.yaml

The command validates ``model/best.pt`` on the held-out test split and writes
the metrics, confusion matrix and representative error examples to
``reports/model_evaluation/``.  It intentionally does not invent values when
the test data is unavailable.
"""

from __future__ import annotations

import argparse
import csv
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Keep Ultralytics settings inside the project on restricted Windows accounts.
# This must be set before importing ``ultralytics``.
os.environ["YOLO_CONFIG_DIR"] = str(ROOT)

import numpy as np
from ultralytics import YOLO

DEFAULT_WEIGHTS = ROOT / "model" / "best.pt"
DEFAULT_OUTPUT = ROOT / "reports" / "model_evaluation"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate the PCB YOLO model on the test split.")
    parser.add_argument("--data", type=Path, default=ROOT / "dataset_final" / "data.yaml")
    parser.add_argument("--weights", type=Path, default=DEFAULT_WEIGHTS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--imgsz", type=int, default=320)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--device", default="cpu", help="'cpu', CUDA index, or CUDA device string")
    return parser.parse_args()


def write_report(path: Path, names: dict[int, str], metrics) -> None:
    box = metrics.box
    rows = []
    for i, name in names.items():
        rows.append((name, float(box.p[i]), float(box.r[i]), float(box.ap50[i]), float(box.ap[i])))

    lines = [
        "# Model Evaluation Report",
        "",
        "Generated by `scripts/evaluate_model.py` on the held-out `test` split.",
        "",
        "## Overall metrics",
        "",
        "| Precision | Recall | mAP50 | mAP50-95 |",
        "|---:|---:|---:|---:|",
        f"| {box.mp:.4f} | {box.mr:.4f} | {box.map50:.4f} | {box.map:.4f} |",
        "",
        "## Per-class metrics",
        "",
        "| Class | Precision | Recall | mAP50 | mAP50-95 |",
        "|---|---:|---:|---:|---:|",
    ]
    lines.extend(f"| {name} | {p:.4f} | {r:.4f} | {ap50:.4f} | {ap:.4f} |" for name, p, r, ap50, ap in rows)
    lines.extend(
        [
            "",
            "## Confusion matrix",
            "",
            "See `confusion_matrix.png` and `confusion_matrix_normalized.png` in this folder.",
            "",
            "## False positives / false negatives",
            "",
            "See `error_examples.csv`. Review its listed images with the generated prediction labels before drawing conclusions about root causes.",
        ]
    )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = parse_args()
    if not args.weights.is_file():
        raise FileNotFoundError(f"Weights not found: {args.weights}")
    if not args.data.is_file():
        raise FileNotFoundError(
            f"Dataset YAML not found: {args.data}. Provide Aya's prepared dataset, then rerun this command."
        )

    args.output.mkdir(parents=True, exist_ok=True)
    model = YOLO(str(args.weights))
    metrics = model.val(
        data=str(args.data),
        split="test",
        imgsz=args.imgsz,
        batch=args.batch,
        device=args.device,
        plots=True,
        save_json=True,
        project=str(args.output.parent),
        name=args.output.name,
        exist_ok=True,
    )

    run_dir = Path(metrics.save_dir)
    # Keep the main report at a stable and predictable path.
    write_report(args.output / "evaluation_results.md", model.names, metrics)
    for image_name in ("confusion_matrix.png", "confusion_matrix_normalized.png"):
        source = run_dir / image_name
        if source.is_file() and source.resolve() != (args.output / image_name).resolve():
            shutil.copy2(source, args.output / image_name)

    # Raw values make the submission auditable and easy to reuse in slides.
    with (args.output / "per_class_metrics.csv").open("w", newline="", encoding="utf-8") as file:
        writer = csv.writer(file)
        writer.writerow(["class", "precision", "recall", "map50", "map50_95"])
        for index, name in model.names.items():
            writer.writerow([name, metrics.box.p[index], metrics.box.r[index], metrics.box.ap50[index], metrics.box.ap[index]])

    # Ultralytics stores validation artifacts (PR curve, F1 curve, confusion
    # matrices and predictions) in the same run directory.  A manifest keeps
    # the handoff explicit instead of relying on a machine-specific run path.
    subprocess.run(
        [
            sys.executable,
            str(ROOT / "scripts" / "analyze_errors.py"),
            "--predictions", str(args.output / "predictions.json"),
            "--images", str(args.data.parent / "test" / "images"),
            "--output", str(args.output),
        ],
        check=True,
    )
    print(f"Evaluation complete: {args.output}")


if __name__ == "__main__":
    main()
